### ISSUE TITLE
Maven support for aar

### ISSUE THREAD

**Issue by wil3** [kedzie/Support_v4_NineOldAndroids#10]
RIght now the artifact in the Maven repo is an apklib file. If would be awesome if there was an aar file so it could be referenced in a gradle build

**Comment by theblang** [comment]
This would be so wonderful.

**Comment by gastonmorixe** [comment]
:+1:

**Comment by kedzie** [comment]
This is closed.  It is in the latest push.  I haven't pushed it to maven central yet but am doing so.
