### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by pietmau** [kedzie/Support_v4_NineOldAndroids#2]

**Comment by kedzie** [comment]
there are some on the github site.  not much more to tell

**Comment by kedzie** [comment]
I updated te documentation

**Comment by kedzie** [comment]
I've added a complete sample application for fragment transactions. It
doesn't have viewpager PageTransformers yet but the docs pretty much
explain that anyway.

You might also want to check out the transition-style branch which adds
support for using XML style resources to specify the transition animations.
 But keep in mind that it is packaged as an APK Library, not a simple jar.
 So you would have to import the project into eclipse and reference it as
an APK Library under project preferences->Android.

**Comment by kedzie** [comment]
im about to push changes to allow speciying anims in style resource.
requires packaging project as apk library, not jar file. read docs.

spread the word!
