### ISSUE TITLE
ActionBarSherlock dependency

### ISSUE THREAD

**Issue by farfromrefug** [kedzie/Support_v4_NineOldAndroids#6]
Hi,

i would like to use your library without ActionBarSherlock. Is that possible?
I still see some ActionBarSherlock dependencies in v4/Gingerbread

**Comment by kedzie** [comment]
Yes it supports using the Navigation Drawer with actionbarsherlock.  In your project u need to add a dependency to actionbarsherlock with an exclusion of android-support-v4.  Look at the sample project for example.
