### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by aali83** [kedzie/Support_v4_NineOldAndroids#8]
I keep getting this error every time I try to import this project into eclipse. Can you please help me solve this, would appreciate it very much! ty!

Cannot nest 'support-v4/src/test/java' inside 'support-v4/src'. To enable the nesting exclude 'test/' from 'support-v4-src'

Reason:
cannot nest 'support-v4/src/test/java' inside 'support-v4/src'. To enable the nesting exclude 'test/' from 'support-v4/src'

**Comment by evp3103** [comment]
Project Properties / Java Build Path / Source / Remove "support-v4/src/test/java"

**Comment by kedzie** [comment]
remove the root src folder as a source folder. you cant have nested source folders. import as a maven project should do this automatically.
